[package]
name = "domain"
version = "0.1.0"
authors = ["tony.0621@hotmail.fr <Thony.0621>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
